// ELE_1492_LED_Display.idl : IDL source for ELE_1492_LED_Display
//

// This file will be processed by the MIDL tool to
// produce the type library (ELE_1492_LED_Display.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(3939C3D8-6094-4CF2-B09B-B5DC33DAD7DC),
	version(1.0),
	helpstring("ELE_1492_LED_Display 1.0 Type Library")
]
library ELE_1492_LED_DisplayLib
{
	importlib("stdole2.tlb");
};
